[MotionPlanners.ENCGIStest]
Enabled = Always
Entity Label = OMPL
Debug Level = Spew
DB Path                                 = /home/nikolai/lststools/dune/misc/re4utmfinalsml.sqlite
Innavigable Layer Name                  = innavigable
Navigable Layer Name                    = navigable

Result DB Path                          = /home/nikolai/lststools/dune/misc/results.sqlite

Start and Goal                          = 536890,7057932,537233,7057474
#Start and Goal                          = 538534,7057539,537233,7057474


Planning Bounds                         = 440732, 6998055, 621256, 7104997