#[Require ntnu-otter-01.ini]

[Sensors.ThelmaHydrophone]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = TBLive
Execution Priority                      = 2
Write full timestamp divider            = 200
Serial Port - Device                    = /dev/ttyUSB0
Serial Port - Baud Rate                 = 115200
Use PPS                                 = true
Sync Period                             = 180.0
Sync Period Ack Timeout                 = 5.0
#Initialization String 0 - Command       = LI=01
#Initialization String 0 - Reply         = 
#Initialization String 1 - Command       = FC=67
#Initialization String 1 - Reply         = 
#Initialization String 2 - Command       = LM=08
#Initialization String 2 - Reply         = 
#Initialization String 3 - Command       = FV?
#Initialization String 3 - Reply         = 



#$1000042,0000000600,TBR Sensor,297,15,29,69,6
#$1000042,0000001200,TBR Sensor,300,17,38,69,7
#$1000042,0000001800,TBR Sensor,303,19,44,69,8
#followed by a couple of R64K and S64K detections.
#$1000042,0000002185,897,R64K,1023,,24,69,9
#$1000042,0000002190,733,R64K,265,,25,69,10
#$1000042,1623050485,615,S64K,1285,12,24,69,11
#$1000042,0000002212,615,S64K,1285,0,18,69,12