[Require ntnu-otter-01.ini]

[Simulators.ThelmaHydrophone]
Enabled                                 = Never
Debug Level                             = None
Entity Label                            = Hydrophone
Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/sampleInput.txt
Delay Between Tag Messages              = 7000

[Simulators.GPS]
#Initial Position                        = 63.3327124836083,10.0742557717784
Initial Position                        = 63.33115233,10.08207277 0.0



# For some reason this does not work
[SourceEstimators.MultipleReceivers]
Enabled                                 = Never
Debug Level                             = None
Entity Label                            = Estimator
Execution Frequency                     = 1
Reference Coordinate					= 63.33, 10.083333
#Initial position of the fish NED wrt Reference Coordinate
Initial Position                        = 0, 0, 0

# Works
[SourceEstimators.FishTagXKF]
Entity Label                            = XKF_FishPosition
Enabled                                 = Never
Debug Level 							= None
Execution Frequency                     = 1
FishPos Cov                             = 1
ToA Cov                                 = 2.0
Depth Cov                               = 0.2
Speed of sound in water [m/s] 			= 1485
Max time shift [ms]						= 500
Reference Coordinate					= 63.334, 10.083333
Initial Position						= 1000, 1000, 70
Receiver Serial Numbers                 = 47, 48, 49

# status unknown
[SourceEstimators.SingleReceiverEKF]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = Estimator632
Ranging - SNR Fit                       = -0.0845, 50.8098
#Ranging - SNR Fit                       = -0.0971, 41.6358
Tag ID                                  = 40
Receiver Serial Number                  = 47
Max Correction Attempts                 = 1
Filter Timestep                         = 7
Qm                                      = 0.1, 0.0, 0.0,
                                          0.0, 0.1, 0.0,
                                          0.0, 0.0, 0.001
Rm                                       = 3.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.2                                          
P0                                        = 3000, -2000, 0,
                                          -2000, 3000, 0,
                                          0, 0, 10
Reference Coordinate					= 63.334, 10.084333

[SourceEstimators.MultipleReceiverXKF]
Entity Label                            = XKFDEMO
Enabled                                 = Never
Debug Level 							= Spew
Execution Frequency                     = 1
FishPos Cov                             = 1
ToA Cov                                 = 2.0
Depth Cov                               = 0.2
Speed of sound in water [m/s] 			= 1485
Max time shift [ms]						= 500
Reference Coordinate					= 63.334, 10.084333
Initial Position						= 1000, 1000, 70
Receiver Serial Numbers                 = 47, 48, 49, 50


[SourceEstimators.MultiReceiverEKF]
Enabled                                 = Never
Debug Level                             = None
Entity Label                            = MultiEKF40
Tag ID                                  = 40
Filter Timestep                         = 1
Reference Coordinate					= 63.334, 10.084333
x0                                      = -445.852850527193, -0.545385405537402, 1.96
ToA Cov                                 = 1.0
Depth Cov                               = 0.1


[Simulators.ThelmaHydrophone]
Enabled                                 = Never
Debug Level                             = None
Entity Label                            = Hydrophone
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/sampleInput.txt
#Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/circleConverge.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_convex.csv
Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/20220303.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_orbital.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_concave.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/forsim2.csv
Delay Between Tag Messages              = 1000

[SourceEstimators.FishTag]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = FishTagEstimator
Filter Timestep                         = 1
x0                                      = 0,0,0
ToA Cov                                 = 1.0
Depth Cov                               = 0.1

[Simulators.FishTag/R1]
Enabled                                 = Always
Transmitter ID                          = 200
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 0.2
Entity Label                            = FishTagR1
Debug Level                             = Spew
#Initial Tag Position                   = 63.334, 10.083333
Initial Tag Position                    = 63.33050479, 10.07735309
Initial Receiver Depth                  = 0
Initial Tag Depth                       = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.00
Time Offset S                           = 0
Receiver Serial                         = 47
Send RemoteSensorInfo                   = true

[Simulators.FishTag/R2]
Enabled                                 = Always
Transmitter ID                          = 200
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 0.2
Entity Label                            = FishTagR2
Debug Level                             = Spew
#Initial Receiver Position               = 63.33240, 10.07408
Initial Tag Position                    = 63.33236354, 10.08578595
Initial Receiver Depth                  = 0
Initial Tag Depth                       = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 48
Send RemoteSensorInfo                   = true

[Simulators.FishTag/R3]
Enabled                                 = Always
Transmitter ID                          = 200
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 0.2
Entity Label                            = FishTagR3
Debug Level                             = Spew
Initial Tag Position                    = 63.32858, 10.08092
Initial Receiver Depth                  = 0
Initial Tag Depth                       = 2
Time Disturbance Mean value             = 0
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 49
Send RemoteSensorInfo                   = true

[Simulators.FishTag/R4]
Enabled                                 = Never
Transmitter ID                          = 200
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 1
Entity Label                            = FishTagR4
Debug Level                             = Spew
Initial Tag Position                        = 63.33046311, 10.08873001
Initial Receiver Depth                  = 0
Initial Tag Depth                       = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 50
Send RemoteSensorInfo                   = true
