############################################################################
# Copyright 2013-2019 Norwegian University of Science and Technology (NTNU)#
# Department of Engineering Cybernetics (ITK)                              #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Faculdade de Engenharia da             #
# Universidade do Porto. For licensing terms, conditions, and further      #
# information contact lsts@fe.up.pt.                                       #
#                                                                          #
# Modified European Union Public Licence - EUPL v.1.1 Usage                #
# Alternatively, this file may be used under the terms of the Modified     #
# EUPL, Version 1.1 only (the "Licence"), appearing in the file LICENCE.md #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# https://github.com/LSTS/dune/blob/master/LICENCE.md and                  #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################
# Author: Nikolai Lauvås                                                   #
############################################################################
# Otter USV 01 configuration file.                                         #
############################################################################

[Require basic.ini]

############################################################################
# General Parameters.                                                      #
############################################################################

[General]
Vehicle                                 = ntnu-otter-01

[Tuning.Autopilot]
Enabled                                 = Always
Entity Label                            = AutopilotTuning
DesiredMPS                              = 0
DesiredHeading                          = 0
SetActive                               = false

[Supervisors.AntiGrounding]
Enabled                                 = Never
Entity Label                            = Map DB
DB Path                                 = /home/nikolai/lststools/dune/misc/combined.sqlite

[Maneuver.Multiplexer]
Debug Level                             = Spew

[Sensors.GPS]
Enabled                                 = Never
Entity Label                            = GPS
Serial Port - Device                    = /dev/ttyUSB0
Serial Port - Baud Rate                 = 19200
Sentence Order                          = GPHDT, GPROT, GPHDM, GPGGA, GPVTG, GPZDA
Debug Level                             = Spew
Initialization String 0 - Command       = $JASC,GPGGA,5\r\n
Initialization String 1 - Command       = $JASC,GPVTG,5\r\n
Initialization String 2 - Command       = $JASC,GPZDA,5\r\n
Initialization String 3 - Command       = $JATT,NMEAHE,0\r\n
Initialization String 4 - Command       = $JASC,GPROT,5\r\n
Initialization String 5 - Command       = $JASC,GPHDT,5\r\n
Initialization String 6 - Command       = $JASC,GPHDM,5\r\n
Initialization String 7 - Command       = $JPPS,WIDTH,999.996,SAVE\r\n
Initialization String 8 - Command       = $JASC,GPHPR,5\r\n
Initialization String 9 - Command       = $JSAVE\r\n

# GPS simulator.
[Simulators.GPS]
Enabled                                 = Hardware
Execution Frequency                     = 1
Entity Label                            = GPS
Number of Satellites                    = 9
HACC                                    = 2
HDOP                                    = 0.9
Activation Depth                        = 0.2
Report Ground Velocity                  = false
Report Yaw                              = false
Initial Position                        = 63.33, 10.083333