############################################################################
# Copyright 2007-2015 Universidade do Porto - Faculdade de Engenharia      #
# Laboratório de Sistemas e Tecnologia Subaquática (LSTS)                  #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Universidade do Porto. For licensing   #
# terms, conditions, and further information contact lsts@fe.up.pt.        #
#                                                                          #
# European Union Public Licence - EUPL v.1.1 Usage                         #
# Alternatively, this file may be used under the terms of the EUPL,        #
# Version 1.1 only (the "Licence"), appearing in the file LICENCE.md       #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################
# Author: Joao Fortuna, Artur Zolich, Krzysztof Cisek                      #
############################################################################
# NTNU-X8-003 configuration file                                           #
############################################################################
[Require ../../etc/common/imc-addresses.ini]
#[Require ../../etc/common/transports.ini]
#[Require uav/transports.ini]
[Require basic.ini]

[General]
Vehicle                                 = ntnu-otter-01 

[SourceEstimators.MultipleReceiverXKF]
Entity Label                            = XKFDEMO
Enabled                                 = Never
Debug Level 							= Spew
Execution Frequency                     = 1
FishPos Cov                             = 1
ToA Cov                                 = 2.0
Depth Cov                               = 0.2
Speed of sound in water [m/s] 			= 1485
Max time shift [ms]						= 500
Reference Coordinate					= 59.302713, 18.217311
Initial Position						= 1000, 1000, 70

[SourceEstimators.FishTagXKF]
Entity Label                            = XKF_FishPosition
Enabled                                 = Always
Debug Level 							= None
Execution Frequency                     = 1
FishPos Cov                             = 1
ToA Cov                                 = 2.0
Depth Cov                               = 0.2
Speed of sound in water [m/s] 			= 1485
Max time shift [ms]						= 500
Reference Coordinate					= 59.302713, 18.217311
Initial Position						= 1000, 1000, 70

[SourceEstimators.MultipleReceiverEKF]
Entity Label                            = EKF_FishPosition
Enabled                                 = Never
Debug Level 							= Debug
Execution Frequency                     = 0.25
FishPos Cov                             = 1
ToA Cov                                 = 2.0
Depth Cov                               = 0.2
Speed of sound in water [m/s] 			= 1485
Max time shift [ms]						= 500
Reference Coordinate					= 59.302713, 18.217311
Initial Position						= 1000, 1000, 70

[Navigation.FishEstimation.TBRTest]
Entity Label                            = Tagsender
Enabled                                 = Always
Execution Frequency                     = 10
Debug Level                             = None

[Transports.Logging]
Enabled                                 = Always
Entity Label                            = Log
Flush Interval                          = 5
LSF Compression Method                  = gzip
Transports                              = RemoteSensorInfo,
										  EstimatedState,
                                          DevDataText,
                                          Announce,
                                          DesiredPath,
                                          TBRFishTag,
										  Reference

[Transports.UDP]
Enabled                                 = Always
Entity Label                            = UDP
Transports                              = DevDataText,
                                          TBRFishTag,
										  RemoteSensorInfo,
										  Acceleration,
                                          AngularVelocity,
                                          AutopilotMode,
                                          CpuUsage,
                                          Current,
                                          ControlLoops,
                                          ControlParcel,
					  			          #CoordConfig,
                                          DesiredPath,
                                          DesiredRoll,
                                          DesiredPitch,
                                          DesiredThrottle,
                                          DesiredSpeed,
                                          DesiredVerticalRate,
                                          DesiredZ,
                                          DesiredVelocity,
                                          DesiredControl,
                                          DesiredHeading,
                                          EntityList,
                                          EntityParameters,
                                          EntityState,
                                          EstimatedState,
                                          EstimatedStreamVelocity,
                                          FollowRefState,
                                          FuelLevel,
                                          GpsFix,
                                          Heartbeat,
                                          IndicatedSpeed,
                                          #LandingPlanGeneration,
                                          LeaderState,
                                          LinkLevel,
                                          LogBookControl,
                                          LoggingControl,
                                          NavigationData,
                                          NavigationUncertainty,
                                          MagneticField,
                                          OperationalLimits,
                                          PathControlState,
                                          PlanControl,
                                          PlanControlState,
                                          PlanDB,
                                          PlanGeneration,
                                          PlanSpecification,
                                          PowerChannelControl,
                                          Pressure,
                                          QueryEntityParameters,
                                          RemoteActionsRequest,
                                          Rpm,
                                          RSSI,
                                          SaveEntityParameters,
                                          SetEntityParameters,
                                          SetServoPosition,
                                          SimulatedState,
                                          StorageUsage,
                                          Target,
                                          Temperature,
                                          TrexOperation,
                                          TrueSpeed,
                                          VehicleMedium,
                                          VehicleState,
                                          Voltage,
                                          #Weight,
                                          GpsFixRtk,
                                          #BeaconDistance,
                                          #ViconPositionEstimates,
                                          EulerAngles,
                                          #FormPos,
                                          #FormCoord,
                                          VelocityDelta,
                                          #CoordinatorState,
                                          DesiredLinearState,
                                          #NetRecoveryState,
									      #DesiredNetRecoveryPath,
									      #NetRecovery,
									      #EstimatedLocalState,
									      ExternalNavData,
									      #NavSources,
									      #RelativeState,
									      Reference
									      #Ping


[Transports.Announce]
Enabled                                 = Always
Entity Label                            = Service Announcer
Activation Time                         = 0
Deactivation Time                       = 0
Debug Level                             = None
Execution Priority                      = 10
Announcement Periodicity                = 10
Enable Loopback                         = 1
Enable Multicast                        = 1
Enable Broadcast                        = 1
Multicast Address                       = 224.0.75.69
Ports                                   = 30100, 30101, 30102, 30103, 30104
Ignored Interfaces                      = eth0:prv

[Transports.Discovery]
Enabled                                 = Always
Entity Label                            = Service Discovery
Activation Time                         = 0
Deactivation Time                       = 0
Debug Level                             = None
Execution Priority                      = 10
Multicast Address                       = 224.0.75.69
Ports                                   = 30100, 30101, 30102, 30103, 30104
Print Incoming Messages                 = false

[Transports.Fragments]
Enabled                                 = Always
Entity Label                            = Message Fragments
Activation Time                         = 0
Deactivation Time                       = 0
Debug Level                             = None
Execution Priority                      = 10
Reception timeout                       = 1800
