
#[Require basic.ini]

############################################################################
# General Parameters.                                                      #
############################################################################
[IMC Addresses]
ntnu-otter-01                           = 0x2810
ntnu-otter-02                           = 0x2811
ntnu-otter-03                           = 0x2812
ntnu-otter-04                           = 0x2813

[General]
Vehicle                                 = ntnu-otter-01
Vehicle Type                            = asv
Speed Conversion -- Actuation           = 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0
Speed Conversion -- RPM                 = 0.0, 120, 245, 360, 490, 615, 725, 845, 980, 980, 980
Speed Conversion -- MPS                 = 0.0, 1.0, 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.09, 3.09, 3.09
Absolute Maximum Depth                  = 0
Time Of Arrival Factor                  = 5.0

[MotionPlanners.OMPL]
Enabled = Always
Entity Label = OMPL
Debug Level = Spew
#DB Path                                 = /home/nikolai/lststools/dune/misc/NO41620.sqlite
#DB Path                                 = /home/nikolai/lststools/dune/misc/combined.sqlite
#DB Path                                 = /home/nikolai/lststools/dune/misc/utm.sqlite
#Innavigable Layer Name                  = lndarePOLYGON
#Navigable Layer Name                    = deparePOLYGON

DB Path                                 = /home/nikolai/lststools/dune/misc/re4utmfinalsml.sqlite
#DB Path                                 = /mnt/ramdisk/re4utmfinal.sqlite

Innavigable Layer Name                  = innavigable
Navigable Layer Name                    = navigable
Search Depth                            = 3

Result DB Path                          = /home/nikolai/lststools/dune/misc/results.sqlite
Benchmark Name                          = Byneset5
Benchmark Runtime                       = 5
Benchmark Max Memory                    = 4000.0
Benchmark Runs                          = 30

# Froan
#Start and Goal                          = 483567, 7082426, 473557, 7079827
#Planning Bounds                         = 473221, 7076546, 485284, 7085058
#Max Planning Time                       = 60

# Entering Nidelven
#Start and Goal                           = 569142, 7035964, 569354, 7032506
#Planning Bounds                          = 568399, 7031678, 571101, 7038044
#Max Planning Time                        = 3600

# Byneset
Start and Goal                          = 569142, 7035964, 561314, 7024321
Planning Bounds                         = 550328, 7014449, 574171, 7041627
Max Planning Time                       = 20

# Extra Long
#Start and Goal                          = 620781, 7100264, 466425, 7003109
#Planning Bounds                         = 440732, 6998055, 621256, 7104997
#Max Planning Time                       = 60

# Long (Not used)
#Start and Goal                          = 548821, 7027691, 510149, 7024390
#Planning Bounds                         = 504116, 7014672, 556559, 7074679
#Max Planning Time                       = 300

# Around Munkholmen
#Start and Goal                          = 568690, 7036674, 569353, 7036689
#Planning Bounds                         = 568524, 7036351, 569645, 7037057
#Max Planning Time                       = 0.5