[Require ntnu-otter-01.ini]

[Simulators.ThelmaHydrophone]
Enabled                                 = Never
Debug Level                             = None
Entity Label                            = Hydrophone2
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/sampleInput.txt
#Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/circleConverge.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_convex.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/20220303.csv
Messagefile Path                        = /home/nikolai/SverreData/sverre_orbital.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_concave.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/forsim2.csv
Delay Between Tag Messages              = 500

[Simulators.ThelmaHydrophone/T2]
Enabled                                 = Always
Debug Level                             = None
Entity Label                            = Hydrophone
Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/sampleInput.txt
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/stryn2022tag1705.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/circleConverge.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_convex.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/20220303.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_orbital.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_concave.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/forsim2.csv
Delay Between Tag Messages              = 1000

[Monitors.SpeedOfSoundInWater]
Enabled                                 = Always
Debug Level                             = None
Entity Label                            = SoundSpeedCalculator
Execution Frequency                     = 0.1
Initial Speed Of Sound                  = 1485
Use Temperature For Speed Of Sound      = true
Initial Temperature                     = 10.0
Initial Salinity                        = 25
Initial Depth                           = 1.0
Temperature - Entity                    = Hydrophone

[SourceEstimators.FishTag]
Enabled                                 = Always
Debug Level                             = None
Entity Label                            = FishTagEstimator
Use Speed Of Sound Measurement          = true
Speed Of Sound - Entity                 = SoundSpeedCalculator
Filter Timestep                         = 0.5
x0                                      = 1,1,1
ToA Cov                                 = 1.0
Depth Cov                               = 0.1
SS - Extra Parameters - Name            = receiver_depth,max_jitter,max_updates_per_new_measurement,max_correction_attempts,interval_mode,tag_period
SS - Extra Parameters - Value           = -0.5,0.01,1,0,1,5

[SourceEstimators.SingleReceiverUKF]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = EstimatorUKF
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 200
Tag Transmitt Period                    = 10
Receiver Serial Number                  = 1000052
Max Correction Attempts                 = 0
Filter Timestep                         = 0.500
Receiver Depth                          = -1.0
Qm                                       = 1.0, 0.0, 0.0,
                                          0.0, 1.0, 0.0,
                                          0.0, 0.0, 1.0
Rm                                       = 1.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.1
P0                                        = 1.0, 0.0, 0.0,
                                            0.0, 1.0, 0.0,
                                            0.0, 0.0, 0.1
Reference Coordinate					= 63.334, 10.084333
Alpha                                   = 0.01
Beta                                    = 2
Kappa                                   = 0

[SourceEstimators.SingleReceiverEKF]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = EstimatorEKF
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 200
Receiver Serial Number                  = 1000052
Tag Transmitt Period                    = 10
Max Correction Attempts                 = 0
Max Updates Per New Measurement         = 1
Filter Timestep                         = 0.500
Receiver Depth                          = -1.0
Qm                                      = 0, 0.0, 0.0,
                                          0.0, 0, 0.0,
                                          0.0, 0.0, 0.001
Rm                                      = 1.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.1                                         
P0                                      = 1, 0, 0,
                                          0, 1, 0,
                                          0, 0, 1
Reference Coordinate					= 63.334, 10.084333

[SourceEstimators.SingleReceiverSRUKF]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = EstimatorSRUKF
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 200
Tag Transmitt Period                    = 10
Receiver Serial Number                  = 1000052
Max Correction Attempts                 = 1
Filter Timestep                         = 0.500
Receiver Depth                          = -1.0
Qm                                       = 1.0, 0.0, 0.0,
                                          0.0, 1.0, 0.0,
                                          0.0, 0.0, 1.0
Rm                                       = 1.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.1
P0                                        = 1.0, 0.0, 0.0,
                                            0.0, 1.0, 0.0,
                                            0.0, 0.0, 1.0
Reference Coordinate					= 63.334, 10.084333
Alpha                                   = 0.01
Beta                                    = 2
Kappa                                   = 0
