[Require ntnu-otter-01.ini]

[Simulators.ThelmaHydrophone]
Enabled                                 = Always
Debug Level                             = None
Entity Label                            = Hydrophone
Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/sampleInput.txt
#Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/circleConverge.csv
Delay Between Tag Messages              = 1000

[SourceEstimators.SingleSource]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = Estimator
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 40
Receiver Serial Number                  = 45
Receiver Depth                          = 3.0
PF - Particles Per Direction            = 50
Max Correction Attempts                 = 1
Filter Timestep                         = 1
EKF - Qm                                = 0.0, 0.0, 0.0,
                                          0.0, 0.0, 0.0,
                                          0.0, 0.0, 0.00001
EKF - Rm                                = 5.8059, 0,
                                          0, 2.1638e6
EKF - P0                                = 66458, -26820, 0,
                                          -26820, 12116, 0,
                                          0, 0, 0

[SourceEstimators.SingleSourceDepth]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = EstimatorwDepth
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 40
Receiver Serial Number                  = 45
PF - Particles Per Direction            = 50
Max Correction Attempts                 = 1
Filter Timestep                         = 1
Receiver Depth                          = 3.0
EKF - Qm                                = 1, 0.0, 0.0,
                                          0.0, 1, 0.0,
                                          0.0, 0.0, 1
EKF - Rm                                = 10.0
#EKF - Rm                                = 5.8059, 0,
#                                          0, 2.1638e6
#EKF - Qm                                = 1.0, 0.0, 0.0,
#                                          0.0, 1.0, 0.0,
#                                          0.0, 0.0, 1.0
#EKF - Rm                                = 10.0, 0.0, 0.0,
#                                          0.0, 500000, 0.0,
#                                          0.0, 0.0, 0.2
EKF - P0                                = 50000, -20000, 1,
                                          -20000, 50000, 1,
                                          1, 1, 10
Reference Coordinate					= 63.32983, 10.07732

[Simulators.FishTag]
Enabled                                 = Never
Execution Frequency                     = 0.142857143
Entity Label                            = FishTag
Initial Position                        = 63.334, 10.083333
Initial Depth                           = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset                             = 0
